"""empty message

Revision ID: bdd192b7e852
Revises: None
Create Date: 2020-01-07 16:52:30.843906

"""

# revision identifiers, used by Alembic.
revision = 'bdd192b7e852'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conditions')
    ### end Alembic commands ###
